# Generated by Django 4.2.1 on 2023-10-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
